/* Songs List */
export const SONGS_BY_ARTIST_REQUEST = 'SONGS_BY_ARTIST_REQUEST';
export const SONGS_BY_ARTIST_SUCCESS = 'SONGS_BY_ARTIST_SUCCESS';
export const SONGS_BY_ARTIST_FAILURE = 'SONGS_BY_ARTIST_FAILURE';

export const SONGS_BY_LANG_REQUEST = 'SONGS_BY_LANG_REQUEST';
export const SONGS_BY_LANG_SUCCESS = 'SONGS_BY_LANG_SUCCESS';
export const SONGS_BY_LANG_FAILURE = 'SONGS_BY_LANG_FAILURE';

export const SONGS_BY_KEYWORD_REQUEST = 'SONGS_BY_KEYWORD_REQUEST';
export const SONGS_BY_KEYWORD_SUCCESS = 'SONGS_BY_KEYWORD_SUCCESS';
export const SONGS_BY_KEYWORD_FAILURE = 'SONGS_BY_KEYWORD_FAILURE';

export const SONGS_BY_ALL_REQUEST = 'SONGS_BY_ALL_REQUEST';
export const SONGS_BY_ALL_SUCCESS = 'SONGS_BY_ALL_SUCCESS';
export const SONGS_BY_ALL_FAILURE = 'SONGS_BY_ALL_FAILURE';

export const FETCH_MENUINFO_REQUEST = 'FETCH_MENUINFO_REQUEST';
export const FETCH_MENUINFO_SUCCESS = 'FETCH_MENUINFO_SUCCESS';
export const FETCH_MENUINFO_FAILURE = 'FETCH_MENUINFO_FAILURE';

export const FETCH_AUDIOTRACK_REQUEST = 'FETCH_AUDIOTRACK_REQUEST';
export const FETCH_AUDIOTRACK_SUCCESS = 'FETCH_AUDIOTRACK_SUCCESS';
export const FETCH_AUDIOTRACK_FAILURE = 'FETCH_AUDIOTRACK_FAILURE';

export const ARTISTS_BY_ARTISTTYPE_REQUEST = 'ARTISTS_BY_ARTISTTYPE_REQUEST';
export const ARTISTS_BY_ARTISTTYPE_SUCCESS = 'ARTISTS_BY_ARTISTTYPE_SUCCESS';
export const ARTISTS_BY_ARTISTTYPE_FAILURE = 'ARTISTS_BY_ARTISTTYPE_FAILURE';

export const ARTISTS_BY_KEYWORD_REQUEST = 'ARTISTS_BY_KEYWORD_REQUEST';
export const ARTISTS_BY_KEYWORD_SUCCESS = 'ARTISTS_BY_KEYWORD_SUCCESS';
export const ARTISTS_BY_KEYWORD_FAILURE = 'ARTISTS_BY_KEYWORD_FAILURE';

export const FILE_EDIT_INFO_REQUEST = 'FILE_EDIT_INFO_REQUEST';
export const FILE_EDIT_INFO_SUCCESS = 'FILE_EDIT_INFO_SUCCESS';
export const FILE_EDIT_INFO_FAILURE = 'FILE_EDIT_INFO_FAILURE';

/* Playlist */
export const LOAD_PLAYLIST_REQUEST = 'LOAD_PLAYLIST_REQUEST';
export const LOAD_PLAYLIST_SUCCESS = 'LOAD_PLAYLIST_SUCCESS';
export const LOAD_PLAYLIST_FAILURE = 'LOAD_PLAYLIST_FAILURE';

export const PLAYLIST_INFO_REQUEST = 'PLAYLIST_INFO_REQUEST';
export const PLAYLIST_INFO_SUCCESS = 'PLAYLIST_INFO_SUCCESS';
export const PLAYLIST_INFO_FAILURE = 'PLAYLIST_INFO_FAILURE';

/* Favorite */
export const SONGS_FROM_FAVORITE_REQUEST = 'SONGS_FROM_FAVORITE_REQUEST';
export const SONGS_FROM_FAVORITE_SUCCESS = 'SONGS_FROM_FAVORITE_SUCCESS';
export const SONGS_FROM_FAVORITE_FAILURE = 'SONGS_FROM_FAVORITE_FAILURE';

/* Lists else */
export const LISTS_ELSE_REQUEST = 'LISTS_ELSE_REQUEST';
export const LISTS_ELSE_SUCCESS = 'LISTS_ELSE_SUCCESS';
export const LISTS_ELSE_FAILURE = 'LISTS_ELSE_FAILURE';

/* Player */
export const PLAY_REQUEST = 'PLAY_REQUEST';
export const PAUSE_REQUEST = 'PAUSE_REQUEST';

export const PLAY_PAUSE_REQUEST = 'PLAY_PAUSE_REQUEST';
export const PLAY_PAUSE_SUCCESS = 'PLAY_PAUSE_SUCCESS';
export const PLAY_PAUSE_FAILURE = 'PLAY_PAUSE_FAILURE';

export const STOP_PLAYER_REQUEST = 'STOP_PLAYER_REQUEST';
export const STOP_PLAYER_SUCCESS = 'STOP_PLAYER_SUCCESS';
export const STOP_PLAYER_FAILURE = 'STOP_PLAYER_FAILURE';

export const NEXT_REQUEST = 'NEXT_REQUEST';
export const NEXT_SUCCESS = 'NEXT_SUCCESS';
export const NEXT_FAILURE = 'NEXT_FAILURE';

export const REPLAY_REQUEST = 'REPLAY_REQUEST';
export const REPLAY_SUCCESS = 'REPLAY_SUCCESS';
export const REPLAY_FAILURE = 'REPLAY_FAILURE';

export const GUIDE_REQUEST = 'GUIDE_REQUEST';
export const GUIDE_SUCCESS = 'GUIDE_SUCCESS';
export const GUIDE_FAILURE = 'GUIDE_FAILURE';

export const EDIT_EFFECT_REQUEST = 'EDIT_EFFECT_REQUEST';
export const EDIT_EFFECT_SUCCESS = 'EDIT_EFFECT_SUCCESS';
export const EDIT_EFFECT_FAILURE = 'EDIT_EFFECT_FAILURE';

export const EDIT_PITCH_REQUEST = 'EDIT_PITCH_REQUEST';
export const EDIT_PITCH_SUCCESS = 'EDIT_PITCH_SUCCESS';
export const EDIT_PITCH_FAILURE = 'EDIT_PITCH_FAILURE';

export const EDIT_MIC_ECHO_REQUEST = 'EDIT_MIC_ECHO_REQUEST';
export const EDIT_MIC_ECHO_SUCCESS = 'EDIT_MIC_ECHO_SUCCESS';
export const EDIT_MIC_ECHO_FAILURE = 'EDIT_MIC_ECHO_FAILURE';

export const EDIT_MIC_VOLUME_REQUEST = 'EDIT_MIC_VOLUME_REQUEST';
export const EDIT_MIC_VOLUME_SUCCESS = 'EDIT_MIC_VOLUME_SUCCESS';
export const EDIT_MIC_VOLUME_FAILURE = 'EDIT_MIC_VOLUME_FAILURE';

export const EDIT_MUSIC_VOLUME_REQUEST = 'EDIT_MUSIC_VOLUME_REQUEST';
export const EDIT_MUSIC_VOLUME_SUCCESS = 'EDIT_MUSIC_VOLUME_SUCCESS';
export const EDIT_MUSIC_VOLUME_FAILURE = 'EDIT_MUSIC_VOLUME_FAILURE';


export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';

export const PUT_REQUEST = 'PUT_REQUEST';
export const PUT_SUCCESS = 'PUT_SUCCESS';
export const PUT_FAILURE = 'PUT_FAILURE';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const DELETE_QUEUE_REQUEST = 'DELETE_QUEUE_REQUEST';
export const DELETE_QUEUE_SUCCESS = 'DELETE_QUEUE_SUCCESS';
export const DELETE_QUEUE_FAILURE = 'DELETE_QUEUE_FAILURE';

export const FETCH_PLAYSTATE_REQUEST = 'FETCH_PLAYSTATE_REQUEST';
export const FETCH_PLAYSTATE_SUCCESS = 'FETCH_PLAYSTATE_SUCCESS';
export const FETCH_PLAYSTATE_FAILURE = 'FETCH_PLAYSTATE_FAILURE';

/* Modal */
export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL';
export const TOGGLE_ADD_TO_FAVORITE_MODAL = 'TOGGLE_ADD_TO_FAVORITE_MODAL';
export const SELECT_FAVORITE = 'SELECT_FAVORITE';
export const TOGGLE_ABOUT_MODAL = 'TOGGLE_ABOUT_MODAL';
export const TOGGLE_TUTORIAL_MODAL = 'TOGGLE_TUTORIAL_MODAL';
export const TOGGLE_SETTING_MODAL = 'TOGGLE_SETTING_MODAL';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const SELECT_AUDIO_OUTPUT = 'SELECT_AUDIO_OUTPUT';

/* Slide Panel */
export const SUBMIT_KEYWORD = 'SUBMIT_KEYWORD';
export const BACK_TO_ARTISTS = 'BACK_TO_ARTISTS';

export const TOGGLE_VIEW = 'TOGGLE_VIEW';
export const SELECT_BOTTON = 'SELECT_BOTTON';

/* System API */
export const GET_THEMES_REQUEST = 'GET_THEMES_REQUEST';
export const GET_THEMES_SUCCESS = 'GET_THEMES_SUCCESS';
export const GET_THEMES_FAILURE = 'GET_THEMES_FAILURE';
export const POST_THEMES_REQUEST = 'POST_THEMES_REQUEST';
export const POST_THEMES_SUCCESS = 'POST_THEMES_SUCCESS';
export const POST_THEMES_FAILURE = 'POST_THEMES_FAILURE';
export const GET_AUDIO_REQUEST = 'GET_AUDIO_REQUEST';
export const GET_AUDIO_SUCCESS = 'GET_AUDIO_SUCCESS';
export const GET_AUDIO_FAILURE = 'GET_AUDIO_FAILURE';
export const POST_AUDIO_REQUEST = 'POST_AUDIO_REQUEST';
export const POST_AUDIO_SUCCESS = 'POST_AUDIO_SUCCESS';
export const POST_AUDIO_FAILURE = 'POST_AUDIO_FAILURE';
export const GET_MIC_REQUEST = 'GET_MIC_REQUEST';
export const GET_MIC_SUCCESS = 'GET_MIC_SUCCESS';
export const GET_MIC_FAILURE = 'GET_MIC_FAILURE';
export const POST_MIC_REQUEST = 'POST_MIC_REQUEST';
export const POST_MIC_SUCCESS = 'POST_MIC_SUCCESS';
export const POST_MIC_FAILURE = 'POST_MIC_FAILURE';
export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAILURE = 'GET_INFO_FAILURE';
export const POST_PLAYER_REQUEST = 'POST_PLAYER_REQUEST';
export const POST_PLAYER_SUCCESS = 'POST_PLAYER_SUCCESS';
export const POST_PLAYER_FAILURE = 'POST_PLAYER_FAILURE';
export const GET_SHARED_REQUEST = 'GET_SHARED_REQUEST';
export const GET_SHARED_SUCCESS = 'GET_SHARED_SUCCESS';
export const GET_SHARED_FAILURE = 'GET_SHARED_FAILURE';
export const POST_SHARED_REQUEST = 'POST_SHARED_REQUEST';
export const POST_SHARED_SUCCESS = 'POST_SHARED_SUCCESS';
export const POST_SHARED_FAILURE = 'POST_SHARED_FAILURE';
export const DELETE_SHARED_REQUEST = 'DELETE_SHARED_REQUEST';
export const DELETE_SHARED_SUCCESS = 'DELETE_SHARED_SUCCESS';
export const DELETE_SHARED_FAILURE = 'DELETE_SHARED_FAILURE';
export const GET_SHARE_REQUEST = 'GET_SHARE_REQUEST';
export const GET_SHARE_SUCCESS = 'GET_SHARE_SUCCESS';
export const GET_SHARE_FAILURE = 'GET_SHARE_FAILURE';

/* Youtube API */
export const GET_YOUTUBE_CATEGORY_REQUEST = 'GET_YOUTUBE_CATEGORY_REQUEST';
export const GET_YOUTUBE_CATEGORY_SUCCESS = 'GET_YOUTUBE_CATEGORY_SUCCESS';
export const GET_YOUTUBE_CATEGORY_FAILURE = 'GET_YOUTUBE_CATEGORY_FAILURE';
export const GET_SONGS_FROM_YOUTUBE_CATEGORY_REQUEST = 'GET_SONGS_FROM_YOUTUBE_CATEGORY_REQUEST';
export const GET_SONGS_FROM_YOUTUBE_CATEGORY_SUCCESS = 'GET_SONGS_FROM_YOUTUBE_CATEGORY_SUCCESS';
export const GET_SONGS_FROM_YOUTUBE_CATEGORY_FAILURE = 'GET_SONGS_FROM_YOUTUBE_CATEGORY_FAILURE';
export const GET_SONGS_FROM_YOUTUBE_DATAAPI_REQUEST = 'GET_SONGS_FROM_YOUTUBE_DATAAPI_REQUEST';
export const GET_SONGS_FROM_YOUTUBE_DATAAPI_SUCCESS = 'GET_SONGS_FROM_YOUTUBE_DATAAPI_SUCCESS';
export const GET_SONGS_FROM_YOUTUBE_DATAAPI_FAILURE = 'GET_SONGS_FROM_YOUTUBE_DATAAPI_FAILURE';
export const GET_PLAYLISTS_FROM_YOUTUBE_DATAAPI_REQUEST = 'GET_PLAYLISTS_FROM_YOUTUBE_DATAAPI_REQUEST';
export const GET_PLAYLISTS_FROM_YOUTUBE_DATAAPI_SUCCESS = 'GET_PLAYLISTS_FROM_YOUTUBE_DATAAPI_SUCCESS';
export const GET_PLAYLISTS_FROM_YOUTUBE_DATAAPI_FAILURE = 'GET_PLAYLISTS_FROM_YOUTUBE_DATAAPI_FAILURE';
export const GET_SONGS_FROM_PLAYLISTS_OF_YOUTUBE_DATAAPI_REQUEST = 'GET_SONGS_FROM_PLAYLISTS_OF_YOUTUBE_DATAAPI_REQUEST';
export const GET_SONGS_FROM_PLAYLISTS_OF_YOUTUBE_DATAAPI_SUCCESS = 'GET_SONGS_FROM_PLAYLISTS_OF_YOUTUBE_DATAAPI_SUCCESS';
export const GET_SONGS_FROM_PLAYLISTS_OF_YOUTUBE_DATAAPI_FAILURE = 'GET_SONGS_FROM_PLAYLISTS_OF_YOUTUBE_DATAAPI_FAILURE';
export const COLLECTION_FROM_YOUTUBE_REQUEST = 'COLLECTION_FROM_YOUTUBE_REQUEST';
export const COLLECTION_FROM_YOUTUBE_SUCCESS = 'COLLECTION_FROM_YOUTUBE_SUCCESS';
export const COLLECTION_FROM_YOUTUBE_FAILURE = 'COLLECTION_FROM_YOUTUBE_FAILURE';

/* WTF Needed */
export const EDIT_SCROLL_POSTION = 'EDIT_SCROLL_POSTION';
export const EDIT_MOUSE_POSTION = 'EDIT_MOUSE_POSTION';
export const TOGGLE_ACTION_PANEL = 'TOGGLE_ACTION_PANEL';
export const TOGGLE_SPECIAL_ACTION_PANEL = 'TOGGLE_SPECIAL_ACTION_PANEL';
export const ADD_MOVE = 'ADD_MOVE';
export const REMOVE_MOVE = 'REMOVE_MOVE';
export const FLASH_DETECT_FAIL = 'FLASH_DETECT_FAIL';
export const FLASH_VERSION_TOO_OLD = 'FLASH_VERSION_TOO_OLD';

/* Language Select */
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

/* SocketIO */
export const EDIT_PLAY_STATE = 'EDIT_PLAY_STATE';
export const EDIT_PITCH_STATE = 'EDIT_PITCH_STATE';
export const EDIT_MUTE_STATE = 'EDIT_MUTE_STATE';
export const EDIT_ECHOMODE_STATE = 'EDIT_ECHOMODE_STATE';
export const EDIT_MIC_STATE = 'EDIT_MIC_STATE';
export const EDIT_MUSIC_STATE = 'EDIT_MUSIC_STATE';
export const EDIT_ISSINGING_STATE = 'EDIT_ISSINGING_STATE';
export const EDIT_AUDIOMPX_STATE = 'EDIT_AUDIOMPX_STATE';
export const EDIT_TVLAUNCH_STATE = 'EDIT_TVLAUNCH_STATE';
export const EDIT_DEVICE_HOT_PLUG_STATE = 'EDIT_DEVICE_HOT_PLUG_STATE';
export const EDIT_NETWORK_ACCESS_STATE = 'EDIT_NETWORK_ACCESS_STATE';

/* Fullscreen */
export const FULLSCREEN_FAILUE = 'FULLSCREEN_FAILUE';

/* Error message */
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
